---
name: Ansible
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # TODO(raypappa): failing until i get community.general installed
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.1.2
        with:
          requirements_file: dev_work_bootstrap/meta/requirements.yml
  verify_ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    # needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Ansible CLI
        uses: tomasnorre/ansible-cli-client@v0.0.7
      - name: Add pyenv to path
        run: |
          echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.goenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.rbenv/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
  verify_macos:
    # needs: check
    strategy:
      matrix:
        os:
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Ansible
        run: |
          brew update
          brew install ansible
      - name: Add pyenv to path
        run: |
          echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.goenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.rbenv/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
