---
name: Ansible
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # TODO(raypappa): failing until i get community.general installed
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.1.2
        with:
          requirements_file: dev_work_bootstrap/meta/requirements.yml
  verify_ubuntu:
    strategy:
      matrix:
        os:
          # Arm debian is broken somehow. not sure why. disabling for now.
          # - ubuntu-24.04-arm
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    # needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Install Python"
        uses: actions/setup-python@v4
      - name: Install Ansible
        run: python -m pip install ansible
      - name: Add pyenv to path
        run: |
          echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.goenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.rbenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.tfenv/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
      - name: "Execute commands"
        run: |
          pyenv version
          goenv version
          rbenv version
          tenv version
          tmux -V
          task --version
          lazydocker --version
          tflint --version
          uv --version
          terraform-docs --version
          glow --version
          vale --version
          aws --version
          sam --version
          aws-vault --version
          kubectl version --client
          fzf --version
          nvim --version
          rgrep --version
          fd --version
          tree-sitter --version
          pnpm --version
          gh --version
          git-checkout-branch -a
          k9s version
          rustc --version
          kustomize version
          cloudflared version
          yq --version
          ct version
          rain version
          mdformat --version
          pre-commit --version
          nvm version
          go version
          npm --version
          tfenv version
  # verify_macos:
  #   # needs: check
  #   strategy:
  #     matrix:
  #       os:
  #         # During this massive push to get everything working. I'm going to disable the amd64 macos until I can get it working.
  #         # - macos-13
  #         - macos-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 2
  #     - name: Install Ansible
  #       run: |
  #         brew update
  #         brew install ansible
  #     - name: Add pyenv to path
  #       run: |
  #         echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
  #         echo "$HOME/.goenv/bin" >> "$GITHUB_PATH"
  #         echo "$HOME/.rbenv/bin" >> "$GITHUB_PATH"
  #     - name: Run Ansible playbook
  #       uses: dawidd6/action-ansible-playbook@v3
  #       with:
  #         playbook: playbook.yaml
  #         directory: ./
  #         options: |
  #           --tags gh
