---
name: Ansible
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.1.2
        with:
          requirements_file: dev_work_bootstrap/meta/requirements.yml
  verify:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Install Python"
        if: ${{ runner.os == 'Linux' }}
        uses: actions/setup-python@v4
      - name: Install Ansible
        if: ${{ runner.os == 'Linux' }}
        run: python -m pip install ansible
      - name: Install Ansible
        if: ${{ runner.os == 'macOS' }}
        # Installing Ansible because testing requires it.
        # However python in gha is not install via brew but python is needed by
        # other dependencies but the link is broken. So in order to fix it we
        # need to unlink python, redo the link, then install python which
        # upgrades python 3.12 and 3.13. Then we can install other things via
        # ansible.
        run: |
          brew update
          brew install ansible
          brew cleanup
          brew unlink python@3.12
          brew link --overwrite python@3.12
          brew install python --skip-link
      - name: Add git dirs to path
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
      - name: "Execute commands"
        run: |
          mise --version
          mise install
          mise ls
