---
name: Ansible
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.1.2
        with:
          requirements_file: dev_work_bootstrap/meta/requirements.yml
  verify:
    # needs: lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Install Python"
        if: ${{ runner.os == 'Linux' }}
        uses: actions/setup-python@v4
      - name: Install Ansible
        if: ${{ runner.os == 'Linux' }}
        run: python -m pip install ansible
      - name: Install Ansible
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install ansible
          brew cleanup
          brew link --overwrite $(brew list --full-name -1 | tr '\n' ' ')
      - name: Add git dirs to path
        run: |
          echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.goenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.rbenv/bin" >> "$GITHUB_PATH"
          echo "$HOME/.tfenv/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
      - name: "Execute commands"
        run: |
          pyenv version
          goenv version
          rbenv version
          tenv version
          tmux -V
          task --version
          lazydocker --version
          tflint --version
          uv --version
          terraform-docs --version
          glow --version
          vale --version
          aws --version
          sam --version
          aws-vault --version
          kubectl version --client
          fzf --version
          nvim --version
          rgrep --version
          fd --version
          tree-sitter --version
          pnpm --version
          gh --version
          k9s version
          rustc --version
          kustomize version
          cloudflared version
          yq --version
          ct version
          rain --version
          mdformat --version
          pre-commit --version
          . $HOME/.nvm/nvm.sh
          nvm version
          npm --version
          export GOENV_ROOT="$HOME/.goenv"
          export PATH="$GOENV_ROOT/bin:$PATH"
          eval "$(goenv init -)"
          export PATH="$GOROOT/bin:$PATH"
          export PATH="$PATH:$GOPATH/bin"
          go version
