---
name: Ansible
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.1.2
        with:
          requirements_file: dev_work_bootstrap/meta/requirements.yml
  verify:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Install Python"
        if: ${{ runner.os == 'Linux' }}
        uses: actions/setup-python@v4
      - name: Install Ansible
        if: ${{ runner.os == 'Linux' }}
        run: python -m pip install ansible
      - name: Install Ansible
        if: ${{ runner.os == 'macOS' }}
        # Installing Ansible because testing requires it.
        # However python in gha is not install via brew but python is needed by
        # other dependencies but the link is broken. So in order to fix it we
        # need to unlink python, redo the link, then install python which
        # upgrades python 3.12 and 3.13. Then we can install other things via
        # ansible.
        run: |
          brew update
          brew install ansible
          brew cleanup
          brew unlink python@3.12
          brew link --overwrite python@3.12
          brew install python --skip-link
      - name: Add git dirs to path
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yaml
          directory: ./
      - name: "Execute commands"
        run: |
          mise --version
          mise install
          uv --version
          aqua --version
          ubi --version
          python --version
          go version
          ruby --version
          terraform -version
          terragrunt -version
          rustc --version
          node --version
          java --version
          groovy --version
          op --version
          aws-vault --version
          kustomize version
          helm version
          packer --version
          krew version
          rain --version
          aws --version
          b2 version
          # beautysh --version
          cloudflared version
          pre-commit --version
          glow --version
          mdformat --version
          fzf --version
          rg --version
          fd --version
          tree-sitter --version
          yq --version
          argocd version
          biome version
          coder version
          conform version
          ruff version
          gh --version
          ct version
          lazygit --version
          lazydocker --version
          k9s version
          jq --version
          pandoc --version
          shfmt --version
          shellcheck --version
          task --version
          vale --version
          trivy --version
          terraform-docs --version
          yamllint --version
          tofu --version
          ytt --version
          xh --version
          tflint --version
          terrascan version
          tf-summarize -v
          terraform-ls --version
          rancher --version
          tmux -V
          nvim --version
          golines --version
          lua -v
          cargo-bininstall -V
          fx --version
          delta --version
          gdu -v
          wtf --version
          visidata --version
          fjira version
          gum --version
          yamlfmt -version
          sam --version
          kubectl version --client
